spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/personalblog?characterEncoding=utf-8&useSSL=false
    jpa:
       show-sql: true

    freemarker:
        suffix: .ftl
        template-loader-path=classpath: /templates
        settings:
            default_encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update